[2018-11-08 20:45:29] [    INFO] --- Setup logging. Log file: ./output/gt1/MNIST/no_cuda=True/08-11-18-20h-45m-29s/logs.txt (setup.py:531)
[2018-11-08 20:45:29] [    INFO] --- Arguments saved to: ./output/gt1/MNIST/no_cuda=True/08-11-18-20h-45m-29s/args.txt (setup.py:534)
[2018-11-08 20:45:29] [    INFO] --- Initialize Tensorboard SummaryWriter (setup.py:539)
[2018-11-08 20:45:32] [ WARNING] --- Git status is ignored! (RunMe.py:205)
[2018-11-08 20:45:32] [    INFO] --- Randomly chosen seed is: 3989785515 (setup.py:616)
[2018-11-08 20:45:32] [    INFO] --- Model CNN_basic expects input size of (32, 32) (my_task.py:84)
[2018-11-08 20:45:32] [   ERROR] --- Unhandled error: NameError("name 'set_up_dataloader' is not defined",) (RunMe.py:261)
[2018-11-08 20:45:32] [   ERROR] --- Traceback (most recent call last):
  File "./template/RunMe.py", line 254, in _execute
    **args.__dict__)
  File "/home/dusan/DeepDIVA/template/runner/my_task/my_task.py", line 87, in single_run
    data_loader, num_classes = set_up_dataloader(model_expected_input_size=model_expected_input_size,
NameError: name 'set_up_dataloader' is not defined
 (RunMe.py:262)
[2018-11-08 20:45:32] [   ERROR] --- Execution finished with errors :( (RunMe.py:263)
